/* Generated By:JJTree: Do not edit this line. ASTReturnStatment.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReturnStatment extends SimpleNode {
  public ASTReturnStatment(int id) {
    super(id);
  }

  public ASTReturnStatment(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ff4eacebc6e4c5f6290825774d7c7aa9 (do not edit this line) */
