/* Generated By:JavaCC: Do not edit this line. CLangTreeConstants.java Version 7.0.5 */
public interface CLangTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSOURCECODEDEF = 1;
  public int JJTPARAMLISTDEF = 2;
  public int JJTPARAMDEF = 3;
  public int JJTFUNCTIONDEF = 4;
  public int JJTVARASSIGNDEFININIT = 5;
  public int JJTVARASSIGNDEF = 6;
  public int JJTVARDEFINEDEF = 7;
  public int JJTSTATEMENTBLOCKDEF = 8;
  public int JJTSTATEMENTDEF = 9;
  public int JJTIFSTATEMENTDEF = 10;
  public int JJTWHILESTATEMENTDEF = 11;
  public int JJTFORSTATEMENTDEF = 12;
  public int JJTEXPRESSIONDEF = 13;
  public int JJTASSIGNEXPRESSIONDEF = 14;
  public int JJTBOOLEXPRESSIONDEF = 15;
  public int JJTBINARYBOOLEXPRESSIONORDEF = 16;
  public int JJTBINARYBOOLEXPRESSIONANDDEF = 17;
  public int JJTBINARYEXPRESSIONEQDEF = 18;
  public int JJTBINARYBOOLOPERATORCOMPAREDEF = 19;
  public int JJTBINARYBOOLEXPRESSIONCOMPAREDEF = 20;
  public int JJTADDEXPRESSIONDEF = 21;
  public int JJTMULEXPRESSIONDEF = 22;
  public int JJTUNARYEXPRESSIONDEF = 23;
  public int JJTCONSTEXPRESSIONDEF = 24;


  public String[] jjtNodeName = {
    "Start",
    "sourceCodeDef",
    "paramListDef",
    "paramDef",
    "functionDef",
    "varAssignDefInInit",
    "varAssignDef",
    "varDefineDef",
    "StatementBlockDef",
    "StatementDef",
    "IfStatementDef",
    "WhileStatementDef",
    "ForStatementDef",
    "expressionDef",
    "assignExpressionDef",
    "boolExpressionDef",
    "binaryBoolExpressionOrDef",
    "binaryBoolExpressionAndDef",
    "binaryExpressionEqDef",
    "binaryBoolOperatorCompareDef",
    "binaryBoolExpressionCompareDef",
    "addExpressionDef",
    "mulExpressionDef",
    "unaryExpressionDef",
    "constExpressionDef",
  };
}
/* JavaCC - OriginalChecksum=1e1168683c1b862bc875ce60503b0494 (do not edit this line) */
