/* Generated By:JavaCC: Do not edit this line. CLangTreeConstants.java Version 7.0.5 */
public interface CLangTreeConstants
{
  public int JJTRETURNSTATMENT = 0;
  public int JJTSTART = 1;
  public int JJTSOURCECODEDEF = 2;
  public int JJTPARAMLISTDEF = 3;
  public int JJTPARAMDEF = 4;
  public int JJTFUNCTIONDEF = 5;
  public int JJTVARASSIGNDEFININIT = 6;
  public int JJTVARASSIGNDEF = 7;
  public int JJTVARDEFINEDEF = 8;
  public int JJTSTATEMENTBLOCKDEF = 9;
  public int JJTSTATEMENTDEF = 10;
  public int JJTIFSTATEMENTDEF = 11;
  public int JJTWHILESTATEMENTDEF = 12;
  public int JJTFORSTATEMENTDEF = 13;
  public int JJTEXPRESSIONDEF = 14;
  public int JJTFUNCTIONCALLDEF = 15;
  public int JJTASSIGNEXPRESSIONDEF = 16;
  public int JJTBOOLEXPRESSIONDEF = 17;
  public int JJTBINARYBOOLEXPRESSIONORDEF = 18;
  public int JJTBINARYBOOLEXPRESSIONANDDEF = 19;
  public int JJTBINARYEXPRESSIONEQDEF = 20;
  public int JJTBINARYBOOLEXPRESSIONCOMPAREDEF = 21;
  public int JJTADDEXPRESSIONDEF = 22;
  public int JJTMULEXPRESSIONDEF = 23;
  public int JJTUNARYEXPRESSIONDEF = 24;
  public int JJTCONSTEXPRESSIONDEF = 25;


  public String[] jjtNodeName = {
    "ReturnStatment",
    "Start",
    "sourceCodeDef",
    "paramListDef",
    "paramDef",
    "functionDef",
    "varAssignDefInInit",
    "varAssignDef",
    "varDefineDef",
    "StatementBlockDef",
    "StatementDef",
    "IfStatementDef",
    "WhileStatementDef",
    "ForStatementDef",
    "expressionDef",
    "functionCallDef",
    "assignExpressionDef",
    "boolExpressionDef",
    "binaryBoolExpressionOrDef",
    "binaryBoolExpressionAndDef",
    "binaryExpressionEqDef",
    "binaryBoolExpressionCompareDef",
    "addExpressionDef",
    "mulExpressionDef",
    "unaryExpressionDef",
    "constExpressionDef",
  };
}
/* JavaCC - OriginalChecksum=ee205c01399865972ca8167dde015663 (do not edit this line) */
